try :
    divided_by_zero = 1/0
    print('Exception happen',divided_by_zero)
except Exception as e:
    print(e)